import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { NormalizedReport, ProjectQualitySummary } from "@quality-report/report-core";
export async function sha256(file: string) { return createHash("sha256").update(await readFile(file)).digest("hex"); }
export async function writeEvidence(output: string, report: NormalizedReport) {
  const included: Array<{ path: string; category: string; sha256: string }> = [];
  for (const item of [...report.downloads].sort((a, b) => a.path.localeCompare(b.path))) { const absolute = path.resolve(output, item.path); if (path.relative(output, absolute).startsWith("..")) continue; try { included.push({ path: item.path, category: item.category, sha256: await sha256(absolute) }); } catch { /* directory */ } }
  for (const item of [{ path: "normalized-report.json", category: "normalized-report" }, { path: "project-quality-summary.json", category: "project-summary" }, { path: "meta/quality-summary.json", category: "human-readable-summary" }]) { try { included.push({ ...item, sha256: await sha256(path.join(output, item.path)) }); } catch { /* optional output */ } }
  included.sort((a,b)=>a.path.localeCompare(b.path));
  const manifest = { schemaVersion: "1.0", project: report.metadata.projectName, release: report.metadata.release, testedBuild: report.metadata.testedBuild, commit: report.metadata.commitSha, branch: report.metadata.branch, workflowRun: report.metadata.workflowRun ?? report.metadata.runId, generatedAt: report.metadata.generatedAt, reportSchemaVersion: report.schemaVersion, toolVersion: "0.1.0", qualityProfile: report.metadata.qualityProfile, automated: report.summary.tests, manual: report.summary.manual, requirements: { covered: report.requirements.covered.length, expected: report.requirements.expected.length, uncovered: report.readiness?.requirements.uncovered ?? report.requirements.missing }, security: report.summary.security, acceptedRisks: report.readiness?.acceptedRisks ?? [], testDefinitionBaseline: report.git?.commit, includedEvidence: included, externalLinks: report.downloads.filter((item) => /^https?:/.test(item.path)).map((item) => item.path).sort(), missingEvidence: report.readiness?.missingEvidence ?? [], locallyDraftedManualWorkExcluded: report.manualExecutions.filter((item) => item.state === "draft").length };
  await writeFile(path.join(output, "evidence-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`); await writeFile(path.join(output, "checksums.sha256"), `${included.map((item) => `${item.sha256}  ${item.path}`).join("\n")}\n`); return manifest;
}
export async function writeProjectSummary(output: string, report: NormalizedReport, reportUrl?: string) {
  const value: ProjectQualitySummary = { schemaVersion: "1.0", projectKey: report.metadata.projectKey ?? report.metadata.projectName, projectName: report.metadata.projectName, release: report.metadata.release, reportUrl, generatedAt: report.metadata.generatedAt, qualityGate: report.qualityGate.status, readiness: report.readiness?.status ?? "incomplete", passedTests: report.summary.tests.passed, failedTests: report.summary.tests.failed + report.summary.tests.broken, newFailures: 0, manualRemaining: report.readiness?.manual.notRun ?? report.summary.manual.notRun, uncoveredRequirements: report.readiness?.requirements.uncovered.length ?? report.requirements.missing.length, securityBlockers: report.readiness?.securityBlockers ?? 0, acceptedRisks: report.readiness?.acceptedRisks.length ?? 0, recommendedActions: report.readiness?.actions.length ?? 0 };
  await writeFile(path.join(output, "project-quality-summary.json"), `${JSON.stringify(value, null, 2)}\n`); return value;
}
