import { describe, expect, it } from "vitest";
import { determineReadiness, ReleaseScopeSchema, sortPortfolio, validateReleaseScopeReferences } from "../src/index.js";
const scope = ReleaseScopeSchema.parse({ release:"2.0", requirements:["REQ-1"], requiredManualCases:["CASE-1"] });
describe("release readiness",()=>{
 it("validates scope and unknown IDs",()=>{ expect(ReleaseScopeSchema.safeParse({release:"2",excludedRequirements:[{id:"REQ-2"}]}).success).toBe(false); expect(validateReleaseScopeReferences(scope,[],[]).map(x=>x.code)).toEqual(["release-scope.unknown-requirement","release-scope.unknown-manual-case"]); });
 it("blocks uncovered and required manual work deterministically",()=>{ const value=determineReadiness({project:"P",scope,tests:[{id:"T-1",status:"passed"}],manualStatuses:{},coveredRequirements:[],security:[],qualityGateStatus:"passed",missingEvidence:["coverage"]}); expect(value.status).toBe("blocked"); expect(value.actions.map(x=>x.type)).toEqual(["manual-test-required","requirement-uncovered","missing-evidence"]); });
 it("does not hide failures accepted as risks",()=>{ const value=determineReadiness({project:"P",scope:{...scope,acceptedRisks:[{id:"RISK-1",reason:"documented"}]},tests:[{id:"T-1",status:"failed"}],manualStatuses:{"CASE-1":"passed"},coveredRequirements:["REQ-1"],security:[],qualityGateStatus:"passed"}); expect(value.actions.map(x=>x.type)).toEqual(["failed-test","accepted-risk"]); expect(value.status).toBe("blocked"); });
 it("supports older reports by treating absent scope as incomplete",()=>{ expect(determineReadiness({project:"P",tests:[],manualStatuses:{},coveredRequirements:[],security:[],qualityGateStatus:"not_evaluated"}).status).toBe("incomplete"); });
});
describe("portfolio",()=>{it("sorts blockers, stale, work, and healthy projects",()=>{ const base={schemaVersion:"1.0" as const,release:"1",generatedAt:"2026-07-14T00:00:00.000Z",qualityGate:"passed" as const,readiness:"ready" as const,passedTests:1,failedTests:0,newFailures:0,manualRemaining:0,uncoveredRequirements:0,securityBlockers:0,acceptedRisks:0,recommendedActions:0}; const result=sortPortfolio([{...base,projectKey:"H",projectName:"Healthy"},{...base,projectKey:"M",projectName:"Manual",manualRemaining:1},{...base,projectKey:"B",projectName:"Blocked",readiness:"blocked"}],new Date("2026-07-15T00:00:00Z")); expect(result.map(x=>x.projectKey)).toEqual(["B","M","H"]); expect(sortPortfolio([{...base,projectKey:"S",projectName:"Stale",generatedAt:"2020-01-01T00:00:00Z"}],new Date("2026-07-15T00:00:00Z"))[0]).toMatchObject({stale:true,priority:2}); });});
