<template>
  <PageHeader title="Manual testing" subtitle="Definitions and imported results are official report data; runner drafts stay only in this browser." />
  <v-tabs v-model="tab"><v-tab value="cases">Manual Cases</v-tab><v-tab value="executions">Manual Executions</v-tab><v-tab value="runner">Manual Runner</v-tab></v-tabs>
  <v-window v-model="tab" class="mt-4">
    <v-window-item value="cases"><v-card v-for="item in manifest?.manualCases ?? []" :key="item.id" class="mb-3" :title="`${item.id} — ${item.title}`"><v-card-subtitle>{{ item.status }} · {{ item.priority }} priority · {{ item.risk }} risk · {{ item.estimatedMinutes ?? "—" }} min</v-card-subtitle><v-card-text><p>{{ item.description }}</p><p><strong>Requirements:</strong> {{ item.requirements.join(", ") || "None" }}</p><p><strong>Tags:</strong> {{ item.tags.join(", ") || "None" }}</p><p v-if="item.status !== 'approved'"><strong>Not active:</strong> only approved cases can be executed.</p><ol><li v-for="(step,index) in item.steps" :key="index"><strong>{{ step.action }}</strong><br />Expected: {{ step.expected }}</li></ol><small>Source: {{ item.sourcePath ?? "n/a" }} · revision {{ item.revision ?? "n/a" }}</small></v-card-text><v-card-actions><v-btn :disabled="item.status !== 'approved'" @click="start(item.id)">Run case</v-btn></v-card-actions></v-card></v-window-item>
    <v-window-item value="executions"><v-alert v-if="!manifest?.manualExecutions.length" type="info" variant="tonal">No imported completed manual executions. Local drafts are not audit evidence.</v-alert><v-card v-for="run in manifest?.manualExecutions ?? []" :key="run.executionId" class="mb-3" :title="run.executionId"><v-card-text>{{ run.tester }} · {{ run.environment }} · build {{ run.testedBuild }}<br />{{ run.cases.length }} case result(s)</v-card-text></v-card></v-window-item>
    <v-window-item value="runner"><v-alert type="warning" variant="tonal" class="mb-3">This browser-local draft is not official evidence until exported and imported by the CLI.</v-alert><v-card v-if="currentCase && draft" :title="`${currentCase.id} — ${currentCase.title}`"><v-card-text>
      <v-row><v-col cols="12" md="6"><v-text-field v-model="draft.executionId" label="Execution ID" @change="save" /></v-col><v-col cols="12" md="6"><v-text-field v-model="draft.release" label="Release or milestone" @change="save" /></v-col><v-col cols="12" md="6"><v-text-field v-model="draft.testedBuild" label="Tested build or commit" @change="save" /></v-col><v-col cols="12" md="6"><v-text-field v-model="draft.environment" label="Environment" @change="save" /></v-col><v-col cols="12" md="6"><v-text-field v-model="draft.tester" label="Tester" @change="save" /></v-col><v-col cols="12" md="6"><v-text-field v-model="draft.sourceCommit" label="Manual case source commit" @change="save" /></v-col></v-row>
      <v-alert v-if="exportErrors.length" type="error" variant="tonal" class="mb-3">{{ exportErrors.join("; ") }}</v-alert><p>{{ completed }} completed · {{ draft.cases.length-completed }} remaining</p>
      <div v-for="(step,index) in currentCase.steps" :key="index" class="mb-4"><strong>{{ index+1 }}. {{ step.action }}</strong><p>Expected: {{ step.expected }}</p><v-btn-toggle v-model="currentResult.steps[index]!.status" mandatory @update:model-value="syncCaseStatus"><v-btn v-for="status in statuses" :key="status" :value="status">{{ status }}</v-btn></v-btn-toggle></div>
      <v-select v-model="currentResult.status" data-testid="case-status" :items="statuses.filter(s=>s!=='not-run')" label="Case result" @update:model-value="setCaseStatus" /><v-textarea v-model="currentResult.actualResult" label="Actual result" @update:model-value="save" /><v-textarea v-model="currentResult.notes" label="Notes" @update:model-value="save" /><v-text-field :model-value="currentResult.defects.join(', ')" label="Defect references (comma-separated)" @update:model-value="v=>{currentResult.defects=split(v);save()}" /><v-text-field :model-value="currentResult.evidence.join(', ')" label="Evidence filenames/references" @update:model-value="v=>{currentResult.evidence=split(v);save()}" />
    </v-card-text><v-card-actions><v-btn :disabled="position===0" @click="position--">Previous</v-btn><v-btn @click="next">Save and next</v-btn><v-btn color="primary" @click="exportResult">Export validated JSON</v-btn><v-btn color="error" variant="text" @click="discard">Discard draft</v-btn></v-card-actions></v-card><v-alert v-else type="info" variant="tonal">Choose “Run case” from an approved Manual Case.</v-alert></v-window-item>
  </v-window>
</template>
<script setup lang="ts">
import { computed, ref, watch } from "vue"; import PageHeader from "../components/PageHeader.vue"; import { draftKey, manualDrafts } from "../services/manualDrafts"; import { calculateCaseStatus, validateManualExecution } from "../services/manualValidation"; import type { Manifest, ManualExecution, ManualStatus } from "../types";
const props=defineProps<{manifest?:Manifest}>(); const tab=ref("cases"); const draft=ref<ManualExecution>(); const position=ref(0); const savedKey=ref(""); const exportErrors=ref<string[]>([]); const statuses:ManualStatus[]=["not-run","passed","failed","blocked","skipped"];
const currentResult=computed(()=>draft.value!.cases[position.value]!); const currentCase=computed(()=>props.manifest?.manualCases.find(c=>c.id===currentResult.value?.caseId)); const completed=computed(()=>draft.value?.cases.filter(c=>c.status!=="not-run").length??0);
function split(v:unknown){return String(v??"").split(",").map(s=>s.trim()).filter(Boolean)} function context(){return{executionId:`manual-${props.manifest?.metadata.runId??"local"}`,projectKey:props.manifest?.metadata.projectName??"project",release:props.manifest?.metadata.runId,testedBuild:props.manifest?.metadata.commitSha??"local-build"}}
function save(){if(!draft.value)return;const next=draftKey(draft.value);if(savedKey.value&&savedKey.value!==next)manualDrafts.remove(savedKey.value);manualDrafts.save(draft.value);savedKey.value=next}
function syncCaseStatus(){currentResult.value.status=calculateCaseStatus(currentResult.value.steps.map(s=>s.status));save()} function setCaseStatus(status:ManualStatus){currentResult.value.steps.forEach(step=>{step.status=status});currentResult.value.status=status;save()}
function start(id:string){const cases=(props.manifest?.manualCases??[]).filter(c=>c.status==="approved");const executionContext=context();draft.value=manualDrafts.find(executionContext)??{schemaVersion:"1.0",...executionContext,environment:"local",tester:"local tester",startedAt:new Date().toISOString(),state:"draft",cases:cases.map(c=>({caseId:c.id,caseRevision:c.revision,status:"not-run",steps:c.steps.map((_,index)=>({index,status:"not-run",evidence:[]})),defects:[],evidence:[]}))};savedKey.value=draftKey(draft.value);position.value=Math.max(0,draft.value.cases.findIndex(c=>c.caseId===id));save();tab.value="runner"}
function next(){save();if(draft.value&&position.value<draft.value.cases.length-1)position.value++} function discard(){if(draft.value)manualDrafts.remove(draftKey(draft.value));draft.value=undefined;savedKey.value=""}
function exportResult(){if(!draft.value)return;draft.value.state="completed";draft.value.completedAt=new Date().toISOString();exportErrors.value=validateManualExecution(draft.value);if(exportErrors.value.length){draft.value.state="draft";draft.value.completedAt=undefined;return}save();const blob=new Blob([JSON.stringify(draft.value,null,2)+"\n"],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`manual-result-${draft.value.projectKey}-${draft.value.executionId}.json`.replace(/[^a-z0-9._-]/gi,"-");a.click();URL.revokeObjectURL(a.href)}
watch(()=>props.manifest,manifest=>{if(!manifest)return;const saved=manualDrafts.find(context());if(saved){draft.value=saved;savedKey.value=draftKey(saved);tab.value="runner"}},{immediate:true});
</script>
